lep-as:
  build: .
  container_name: lep-as
  ports:
  - "80:8080"
  links:
  - "lep-db:mysql-db"
lep-db:
  image: mysql:5.7
  container_name: lep-db
  environment:
  - MYSQL_ROOT_PASSWORD=adminpwd
  - MYSQL_USER=lportal
  - MYSQL_PASSWORD=lportal
  - MYSQL_DATABASE=lportal
